name: ORY's Nancy for GitHub Actions
author: 'ORY'
description: 'Run Sonatype Nancy as part of your GitHub Actions workflow.'
inputs:
  target:
    description: 'This is the path to the go.sum or Gopkg.lock file.'
    required: false
    default: 'go.sum'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}

branding:
  icon: 'shield'
  color: 'gray-dark'
